// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZkMFMPh5XEW6I_Ibi3VOt6dX3ukj1ETc',
    appId: '1:226940852229:web:b01518c80cbefbc5c8a46c',
    messagingSenderId: '226940852229',
    projectId: 'flutter-chat-app-363b6',
    authDomain: 'flutter-chat-app-363b6.firebaseapp.com',
    storageBucket: 'flutter-chat-app-363b6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJLw3-5F4aKoMLfer3hAl0ST6D57AOODI',
    appId: '1:226940852229:android:354ba13e3b9526dfc8a46c',
    messagingSenderId: '226940852229',
    projectId: 'flutter-chat-app-363b6',
    storageBucket: 'flutter-chat-app-363b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzFY5tYyUuU0LmBltVxkgBRaj9hir_pQU',
    appId: '1:226940852229:ios:c59a81790b27f918c8a46c',
    messagingSenderId: '226940852229',
    projectId: 'flutter-chat-app-363b6',
    storageBucket: 'flutter-chat-app-363b6.appspot.com',
    iosClientId: '226940852229-b9r2vhbut66kmdhjf86bvpuvltgsuoct.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzFY5tYyUuU0LmBltVxkgBRaj9hir_pQU',
    appId: '1:226940852229:ios:c59a81790b27f918c8a46c',
    messagingSenderId: '226940852229',
    projectId: 'flutter-chat-app-363b6',
    storageBucket: 'flutter-chat-app-363b6.appspot.com',
    iosClientId: '226940852229-b9r2vhbut66kmdhjf86bvpuvltgsuoct.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
